# Generated by Django 2.2.1 on 2020-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='sump',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='pic',
            field=models.FileField(max_length=64, upload_to='movie_cover', verbose_name='封面图片'),
        ),
    ]
