from django.urls import path
from user import views

urlpatterns = [
    path("", views.all_cafeteria, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    # path("item/", views.item, name="item"),
    path("all_cafeteria/", views.all_cafeteria, name="all_cafeteria"),
    path("cafeteria/<int:cafeteria_id>/", views.cafeteria, name="cafeteria"),
    path("score/<int:cafeteria_id>/", views.score, name="score"),
    path("comment/<int:cafeteria_id>/", views.commen, name="comment"),
    path("good/<int:commen_id>/<int:cafeteria_id>/", views.good, name="good"),
    path("collect/<int:cafeteria_id>/", views.collect, name="collect"),
    path("decollect/<int:cafeteria_id>/", views.decollect, name="decollect"),
    path("personal/", views.personal, name="personal"),
    path("mycollect/", views.mycollect, name="mycollect"),
    path("myjoin/", views.myjoin, name="myjoin"),
    path("my_comments/", views.my_comments, name="my_comments"),
    path("my_rate/", views.my_rate, name="my_rate"),
    path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
    path("delete_rate/<int:rate_id>", views.delete_rate, name="delete_rate"),
    path("hot_cafeteria/", views.hot_cafeteria, name="hot_cafeteria"),
    path("latest_cafeteria/", views.latest_cafeteria, name="latest_cafeteria"),
    path("search/", views.search, name="search"),
    path("golden_horse/", views.golden_horse, name="golden_horse"),
    path("oscar/", views.oscar, name="oscar"),
    path("begin/", views.begin, name="begin"),
    path("kindof/", views.kindof, name="kindof"),
    path("kind/<int:kind_id>/", views.kind, name="kind"),
    path("week_reco/", views.reco_by_week, name="week_reco"),
    path("monthitem/", views.reco_by_week, name="monthitem"),
]
